(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "grizzl")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "robe")
(depends-on "smartparens")
