(source melpa)

(depends-on "ag")
(depends-on "auto-complete")
(depends-on "enh-ruby-mode")
(depends-on "grizzl")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "rbenv")
(depends-on "rinari")
(depends-on "robe")
(depends-on "smartparens")
(depends-on "web-mode")
